name: hello actions

on: 
  workflow_dispatch:
  push:
    branches:
     - gh-action-1

jobs:
  hello-actions:
    runs-on: ubuntu-20.04
    steps:
      - name: say-hello
        run: echo "hello, actions!"
